branches:
  only:
    - main
environment:
  matrix:
  - platform: x86
  - platform: x64
  
build: false

skip_tags: true

install:
  - echo Installed Pythons
  - dir c:\Python*

  - ps: |
      if ($env:platform -Match "x86") 
      {
        $env:PYTHON="C:\Python38\python"
        $env:PATH += ';C:\msys64\mingw32\bin'
      }
      elseif ($env:platform -Match "x64") 
      {
        $env:PYTHON="C:\Python38-x64\python"
        $env:PATH += ';C:\msys64\mingw64\bin'
      }
  - ps: |
      iex "$env:PYTHON -m pip install pip==21.3.1"
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
  - ps: |
      iex "$env:PYTHON -m pip install -r test-time-requirements.txt"
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
  - ps: |
      iex "$env:PYTHON -m pip install -e ."
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
test_script:
  - ps: |
      iex "$env:PYTHON -m pytest -We -p no:unraisableexception tests/unit_tests"
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
