[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "PySuperDropletLES"
description = "TODO"
readme = "README.md"
requires-python = ">=3.10"
keywords = ["TODO", "TODO"]
license = {text = "GPL-3.0"}
classifiers = [
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Topic :: Scientific/Engineering",
        "Topic :: Scientific/Engineering :: Atmospheric Science",
        "Topic :: Scientific/Engineering :: Mathematics",
        "Topic :: Scientific/Engineering :: Physics"
]
dependencies = [
    "numba_mpi>=0.26",
    "PySDM",
    "PyMPDATA",
    "mpi4py",
    "h5py"
]
dynamic = ["version"]

